//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
	using System.Web.Mvc;
	using System.ComponentModel.DataAnnotations;

	public partial class Item
    {
		[HiddenInput(DisplayValue = false)]
		public int Id { get; set; }
		[Display(Name = "Название")]
		[Required(ErrorMessage = "Пожалуйста, введите название наименование")]
		public string Name { get; set; }
		[Display(Name = "Категория")]
		[Required(ErrorMessage = "Пожалуйста, укажите категорию")]
		public string Category { get; set; }
		[DataType(DataType.MultilineText)]
		[Display(Name = "Описание")]
		[Required(ErrorMessage = "Пожалуйста, введите описание")]
		public string Description { get; set; }
		[Display(Name = "Цена (руб)")]
		[Range(0.01, double.MaxValue, ErrorMessage = "Пожалуйста, введите положительное значение для цены")]
		public Nullable<double> Price { get; set; }
		[DataType(DataType.MultilineText)]
		[Display(Name = "Полное описание")]
		[Required(ErrorMessage = "Пожалуйста, введите описание")]
		public string FullDescription { get; set; }
    }
}
